### ISSUE TITLE
Use package-local nicknames

### ISSUE THREAD

**Issue by phoe** [DanielKeogh/persistent-vector#1]
> For the convenience of using this library without conflicting with other packages, functions that transform or read from vectors are prefixed with `v-`.

You don't need to do that - you can (and should) have your users leverage package-local nicknames instead of installing a global `pv` nickname. Then users of your library can install a `pv` local nickname themselves and use symbols from your package via `pv:length`, `pv:append` and so on.

**Comment by DanielKeogh** [comment]
Huh. I missed the package-local nicknames announcement. I guess that completely changes how I design lisp API's.

Closing, because I removed the prefixes/global package nicknames.
