### ISSUE TITLE
Untabify

### ISSUE THREAD

**Issue by phoe** [DanielKeogh/persistent-vector#2]
Your code and README currently use a mix of tabs and spaces, which causes issues with differing tab lengths.

![Zrzut ekranu z 2022-01-13 12-18-13](https://user-images.githubusercontent.com/15045546/149320881-923e6e72-77a5-4407-9bdb-fea8eadb6f6e.png)

A suggested fix is to convert everything to spaces.

**Comment by DanielKeogh** [comment]
Converted all of the tabs in README.md to spaces.

**Comment by phoe** [comment]
Just to be clear - Lisp files would also welcome that treatment, even if currently they look OK on GitHub.
