### ISSUE TITLE
Maybe rename FOR to something MAPesque

### ISSUE THREAD

**Issue by phoe** [DanielKeogh/persistent-vector#3]
https://github.com/DanielKeogh/persistent-vector/blob/29974e874eaea2dca464bf86bd413fc2a2f1b2a1/api.lisp#L60-L65

If we'd like to be consistent with CL naming, then I'd suggest using `map` instead of `for` for a function that is supposed to iterate over the vector in a predictable order and funcall a function on each of its elements.

**Comment by DanielKeogh** [comment]
`map` isn't quite right for this case because it isn't aggregating a result.
I think I'll just replace it anyway a `dovector` macro that doesn't require a lambda.

**Comment by phoe** [comment]
The `map` functions don't need to aggregate results - see e.g. `(map nil #'print #(1 2 3 4 5))` or `(mapc #'print '(1 2 3 4 5))`.

But, sure, a `dofoo` macro also works.
