### ISSUE TITLE
DEFCONSTANT must be wrapped in EVAL-ALWAYS

### ISSUE THREAD

**Issue by phoe** [DanielKeogh/persistent-vector#4]
https://github.com/DanielKeogh/persistent-vector/blob/29974e874eaea2dca464bf86bd413fc2a2f1b2a1/persistent-vector.lisp#L12

This will fail on CCL because according to the CL specification the value of the constant does not necessarily need to be available in the same file where that constant is defined, and CCL does things this way. A fix is to wrap all `defconstant` and neighboring forms in `(eval-when (:compile-toplevel :load-toplevel :execute) ...)`

**Comment by DanielKeogh** [comment]
Wrapped constants in `(eval-when (:compile-toplevel :load-toplevel :execute)...)` for greate goode.

Thanks phoe :)
