### ISSUE TITLE
Invalid initarg types in DEFSTRUCT

### ISSUE THREAD

**Issue by phoe** [DanielKeogh/persistent-vector#5]
https://github.com/DanielKeogh/persistent-vector/blob/29974e874eaea2dca464bf86bd413fc2a2f1b2a1/persistent-vector.lisp#L21-L25

`NIL` is not of type `FIXNUM` or `VECTOR-NODE` or `SIMPLE-ARRAY` and therefore it shouldn't be the initial value for any of these fields. Try using `(alexandria:required-argument :foo)` instead for an error if a constructor argument is meant to be required.

This applies to the rest of `defstruct`s as well.

**Comment by DanielKeogh** [comment]
Cleaned up the struct definitions. Ty
