### ISSUE TITLE
Printing does not respect *PRINT-LENGTH*

### ISSUE THREAD

**Issue by phoe** [DanielKeogh/persistent-vector#7]
https://github.com/DanielKeogh/persistent-vector/blob/29974e874eaea2dca464bf86bd413fc2a2f1b2a1/persistent-vector.lisp#L508

The printing code should respect `*print-length*` and truncate printed representations with `...` in the same way the Lisp printer already works for lists and arrays.

**Comment by DanielKeogh** [comment]
And fixed. :)
